maxmemory 512mb                     # limite massimo di RAM che Redis può usare
maxmemory-polixy allkeys-lfu        # strategia di eviction quando la memoria è piena, Least Frequently Used
save ""                             # snapshot RDB, salva se almeno 1 chiave è cambiata in 900s. In scenari cache pura → spesso si disabilita
appendonly no                       # abilita AOF (Append Only File) per persistenza più sicura. In scenari cache pura → spesso si disabilita
requirepass supersecret             # password per autenticazione